name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      buildArgs: version=3.1.6-2019-10-23-2de4665c6
      run: docker build . --file Dockerfile --tag docker-connectiq :$(date +%s)
